### PR TITLE
Adds the run-app command to override the sketch wrapping

### PR DESCRIPTION
**Pull request by pedrozath**
Adds a new option scoped for those who want to just want to build full jRuby apps that use Ruby Processing. It discards the whole Processing class wrapping logic.

### CODE REVIEW

**Comment by monkstone** [comment]
OK I'm not sure what this adds, in my hands JWishy will run just fine whether class wrapped or not with
`rp5 run jwishy`
However JWishy not class wrapped won't run with
`rp5 run-app jwishy` (this is because `library_loader` won't work without being wrapped)
Wrap JWishy as a class and it runs OK with
`rp5 run-app jwishy`, but whats the benefit?

**Comment by pedrozath** [comment]
Hi Monk. I have a t-shirt store that sells t-shirts with art generated by ruby-processing (http://entrama.com.br). For that, I really need the PDF exporting support, which I found lacking (or buggy) in Processing 3.0.

Second, I'm developing a Java FX visual interface (with JRuby FX) to generate drawings for my brand and to do that, I had to get rid of the sketch wrapping features of Processing. I know processing has this "sketchy" but I believe it's a powerful tool that can be used inside apps to do really useful stuff.

So I've introduced the run-app command in order to give the users the ability of running actual apps that have ruby-processing as main library and not just processing sketches. I could have suggested something like "rp5 run sketch.rb --no-wrap" but I though it would mix two actually different use cases. Run would be for sketches while Run-app would be for actual Ruby Applications.

What do you think? 

Also, I really love this project and it'd be an honour for me to take it on.

**Comment by pedrozath** [comment]
I pasted an example of the code here so you can see the kind of file I'm running through run-app command:

https://gist.github.com/pedrozath/b08c1cf4d1d49c637d33ec4c5fcfcb66

**Comment by monkstone** [comment]
That looks quite interesting, I should look into javafx a bit more myself, you might be interested in a side project I started [propane](https://github.com/monkstone/propane) _which is essentially ruby-processing but with java jars included in the gem_, where class wrapped sketches can be run directly with jruby (I have also updated to JRuby9K).
Anyway I would love for someone to take on ruby-processing @jashkenas can you invite @pedrozath 
onto ruby-processing, with a view to him getting commit access in first instance and if it works out ability to push to rubygems.

**Comment by monkstone** [comment]
@pedrozath seems jashkenas might have gone bit quiet on internet no evidence of action on twitter or coffeescript so I decided just to pull your request, I have some ideas for improving watch mode that seem to work better on ruby-processing rather than on jruby-art so I might like to release a version with your PR before I do that.

**Comment by pedrozath** [comment]
Alright, i'll do it. 

Btw, the propane idea is very interesting. However, to my needs, a cool thing would be like a processing framework, like rails, withy JavaFX as a quick way to introduce GUI panels and so on. What do you think about this idea?

**Comment by pedrozath** [comment]
Just edited and added it: https://github.com/jashkenas/ruby-processing/wiki/Getting-Started

**Pull request merged**
